[build]
command = "npm run build"
functions = "netlify/functions"
publish = "dist"

[build.environment]
NODE_VERSION = "20"
NPM_VERSION = "9.9.4"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
