
[build]
  command = "npm install --legacy-peer-deps --production=false && npm run build"
  publish = "dist"
  functions = "dist/netlify/functions"

[build.environment]
  NODE_VERSION = "22"
  NODE_ENV = "production"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
