[build]
  command = "npm install && npm run compile:migrations && npm run compile:functions && npm run migrate && vite build"
  functionsDirectory = "dist/netlify/functions"
  publish = "dist"

[context.production.environment]
  NPM_FLAGS = "--include=dev"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
