[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

[dev]
  framework   = "vite"
  publish     = "dist"
  functions   = "netlify/functions"
  targetPort  = 5173

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200