[build]
  command = "npm install --include=dev && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[context.production.environment]
  NPM_FLAGS = "--include=dev"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
