[build]
  # Install dev dependencies so the vite build tool is available
  command = "npm install --include=dev && npm run migrate && npm run compile:functions && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "22"
  NODE_ENV = "production"
  AUTH0_AUDIENCE = "https://mindxdo.netlify.app/api"
  AUTH0_ISSUER = "https://dev-8s7m3hg5gjlugoxd.us.auth0.com/"

[context.production.environment]
  AUTH0_AUDIENCE = "https://mindxdo.netlify.app/api"
  AUTH0_ISSUER = "https://dev-8s7m3hg5gjlugoxd.us.auth0.com/"

[context.deploy-preview.environment]
  AUTH0_AUDIENCE = "https://mindxdo.netlify.app/api"
  AUTH0_ISSUER = "https://dev-8s7m3hg5gjlugoxd.us.auth0.com/"

[context.branch-deploy.environment]
  AUTH0_AUDIENCE = "https://mindxdo.netlify.app/api"
  AUTH0_ISSUER = "https://dev-8s7m3hg5gjlugoxd.us.auth0.com/"

[context.dev.environment]
  AUTH0_AUDIENCE = "https://mindxdo.netlify.app/api"
  AUTH0_ISSUER = "https://dev-8s7m3hg5gjlugoxd.us.auth0.com/"

[[redirects]]
  from = "/api/maps/:id"
  to = "/.netlify/functions/mapid"
  status = 200

[[redirects]]
  from = "/api/kanban/boards"
  to = "/.netlify/functions/kanban-boards"
  status = 200

[[redirects]]
  from = "/api/kanban/board-data"
  to = "/.netlify/functions/kanban-board-data"
  status = 200

[[redirects]]
  from = "/api/kanban/columns"
  to = "/.netlify/functions/kanban-columns"
  status = 200

[[redirects]]
  from = "/api/kanban/columns/:id"
  to = "/.netlify/functions/kanban-columns/:id"
  status = 200

[[redirects]]
  from = "/api/kanban/cards"
  to = "/.netlify/functions/kanban-cards"
  status = 200

[[redirects]]
  from = "/api/kanban/cards/:id/move"
  to = "/.netlify/functions/kanban-cards/:id/move"
  status = 200

[[redirects]]
  from = "/api/kanban/cards/:id"
  to = "/.netlify/functions/kanban-cards/:id"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
