
[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.20.8"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
