[build]
  command   = "npm run compile:migrations && npm run compile:functions && npm run migrate && npm run build"
  publish   = "dist"
  functions = "dist/netlify/functions"

[context.production.environment]
  NPM_FLAGS = "--include=dev"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
