[build]
  command   = "npm install ts-node && ts-node runmigrations.ts && npm run build"
  publish   = "dist"
  functions = "netlify/functions"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
