ALTER TABLE nodes ADD COLUMN IF NOT EXISTS x DOUBLE PRECISION DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS y DOUBLE PRECISION DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS label TEXT;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS parent_id UUID REFERENCES nodes(id) ON DELETE SET NULL;
